# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gpt_assist.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GPT_YYDS(object):
    def setupUi(self, GPT_YYDS):
        GPT_YYDS.setObjectName("GPT_YYDS")
        GPT_YYDS.resize(947, 656)
        self.centralwidget = QtWidgets.QWidget(GPT_YYDS)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 121, 51))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 410, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(60, 100, 351, 291))
        self.groupBox.setObjectName("groupBox")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(20, 30, 311, 241))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 20, 60, 60))
        self.pushButton_2.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_2.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_2.setStyleSheet("border-image: url(:/button/microphone.png);\n"
"background-color: rgb(217, 243, 255);\n"
"border-radius: 30px;\n"
"border-style: outset;")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 410, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(460, 40, 431, 531))
        self.groupBox_2.setObjectName("groupBox_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_2)
        self.textBrowser.setGeometry(QtCore.QRect(20, 30, 391, 241))
        self.textBrowser.setObjectName("textBrowser")
        self.image_label = QtWidgets.QLabel(self.groupBox_2)
        self.image_label.setGeometry(QtCore.QRect(110, 300, 200, 200))
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        GPT_YYDS.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GPT_YYDS)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 947, 26))
        self.menubar.setObjectName("menubar")
        GPT_YYDS.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GPT_YYDS)
        self.statusbar.setObjectName("statusbar")
        GPT_YYDS.setStatusBar(self.statusbar)

        self.retranslateUi(GPT_YYDS)
        self.pushButton.clicked.connect(GPT_YYDS.getGPT) # type: ignore
        self.pushButton_3.clicked.connect(GPT_YYDS.getBaidu) # type: ignore
        self.pushButton_2.clicked.connect(GPT_YYDS.baiduInput) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(GPT_YYDS)

    def retranslateUi(self, GPT_YYDS):
        _translate = QtCore.QCoreApplication.translate
        GPT_YYDS.setWindowTitle(_translate("GPT_YYDS", "MainWindow"))
        self.label.setText(_translate("GPT_YYDS", "智能助理"))
        self.pushButton.setText(_translate("GPT_YYDS", "GPT yyds!"))
        self.groupBox.setTitle(_translate("GPT_YYDS", "输入在这里"))
        self.pushButton_3.setText(_translate("GPT_YYDS", "百度AI绘图"))
        self.groupBox_2.setTitle(_translate("GPT_YYDS", "输出看这里"))
from qt_resource.qt_pic_test1 import pic1_rc
