# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'highlightUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Highlight_code(object):
    def setupUi(self, Highlight_code):
        Highlight_code.setObjectName("Highlight_code")
        Highlight_code.resize(1055, 733)
        self.centralwidget = QtWidgets.QWidget(Highlight_code)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 90, 981, 171))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(180, 50, 131, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 50, 111, 31))
        self.pushButton.setObjectName("pushButton")
        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setGeometry(QtCore.QRect(40, 310, 961, 351))
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        Highlight_code.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Highlight_code)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1055, 26))
        self.menubar.setObjectName("menubar")
        Highlight_code.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Highlight_code)
        self.statusbar.setObjectName("statusbar")
        Highlight_code.setStatusBar(self.statusbar)

        self.retranslateUi(Highlight_code)
        self.pushButton.clicked.connect(Highlight_code.codeHighlight) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Highlight_code)

    def retranslateUi(self, Highlight_code):
        _translate = QtCore.QCoreApplication.translate
        Highlight_code.setWindowTitle(_translate("Highlight_code", "MainWindow"))
        self.label.setText(_translate("Highlight_code", "<html><head/><body><p><span style=\" font-size:16pt;\">你的代码：</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("Highlight_code", "python"))
        self.comboBox.setItemText(1, _translate("Highlight_code", "java"))
        self.comboBox.setItemText(2, _translate("Highlight_code", "c++"))
        self.comboBox.setItemText(3, _translate("Highlight_code", "html"))
        self.pushButton.setText(_translate("Highlight_code", "高亮!"))
